# Change the default theme to be use when building the site with Hugo
baseURL = "http://localhost:1313"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "hugo-theme-learn"

# Enable multilingual mode
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = ""
  description = ""
  author = "journeyoftheaverageguy@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  
[Languages]
[Languages.en]
title = "Serverless Invoice Reading and Storage System"
weight = 1
languageName = "English"
contentDir = "content"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

[Languages.vi]
title = "Hệ Thống Đọc và Lưu Trữ Hóa Đơn Serverless"
weight = 2
languageName = "Tiếng Việt"
contentDir = "content"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

